openapi: 3.0.0
info:
  title: Common Platform API Case URL Mapper
  description: Case URL Mapper specification
  version: 0.1.0
  contact:
    email: no-reply@hmcts.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
paths:
  /urnmapper/{case_urn}:
    get:
      description: Retrieve details of a case ID by case URN.
      operationId: getCaseIdByCaseUrn
      tags:
        - case ID by case URN
      parameters:
        - in: path
          name: case_urn
          required: true
          description: Unique reference number for the case
          schema:
            type: string
        - in: query
          name: refresh
          required: false
          description: Refresh flag for cache
          schema:
            type: boolean
      responses:
        '200':
          description: Case found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CaseMapperResponse"
        '400':
          description: Bad input parameter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    CaseMapperResponse:
      type: object
      required:
        - caseUrn
      properties:
        caseId:
          description: Case ID
          type: string
          example: "CASE-ID-EXAMPLE"
        caseUrn:
          description: Unique reference number for the case
          type: string
          example: "CASE-URN-EXAMPLE"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Machine-readable error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          additionalProperties: true
          description: Additional error context
        timestamp:
          type: string
          format: date-time
        traceId:
          type: string
          description: Unique identifier for error tracing
